// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKeFW29YBTQhXXd1T5xL-NLMiW1csFho',
    appId: '1:886510659088:web:d58f2162b8dee1c358cc95',
    messagingSenderId: '886510659088',
    projectId: 'dry-cleaning-b7a6b',
    authDomain: 'dry-cleaning-b7a6b.firebaseapp.com',
    databaseURL: 'https://dry-cleaning-b7a6b-default-rtdb.firebaseio.com',
    storageBucket: 'dry-cleaning-b7a6b.appspot.com',
    measurementId: 'G-72J1XGYMGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3Cp4CEYEXO8AMM_imohZc2IVV6q4g-I',
    appId: '1:886510659088:android:1680567d098f0d8458cc95',
    messagingSenderId: '886510659088',
    projectId: 'dry-cleaning-b7a6b',
    databaseURL: 'https://dry-cleaning-b7a6b-default-rtdb.firebaseio.com',
    storageBucket: 'dry-cleaning-b7a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBa7XmtIqgILxyVgr5lFKIBVqfePLeoE',
    appId: '1:886510659088:ios:2ae34c5eed8262d858cc95',
    messagingSenderId: '886510659088',
    projectId: 'dry-cleaning-b7a6b',
    databaseURL: 'https://dry-cleaning-b7a6b-default-rtdb.firebaseio.com',
    storageBucket: 'dry-cleaning-b7a6b.appspot.com',
    androidClientId: '886510659088-mf7g2ms0qnkh90ucqnfmao5ir38ci1oj.apps.googleusercontent.com',
    iosClientId: '886510659088-9ntjdlmcesaloni35p1jng7lhqfgg8ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.dryCleaning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfBa7XmtIqgILxyVgr5lFKIBVqfePLeoE',
    appId: '1:886510659088:ios:2ae34c5eed8262d858cc95',
    messagingSenderId: '886510659088',
    projectId: 'dry-cleaning-b7a6b',
    databaseURL: 'https://dry-cleaning-b7a6b-default-rtdb.firebaseio.com',
    storageBucket: 'dry-cleaning-b7a6b.appspot.com',
    androidClientId: '886510659088-mf7g2ms0qnkh90ucqnfmao5ir38ci1oj.apps.googleusercontent.com',
    iosClientId: '886510659088-9ntjdlmcesaloni35p1jng7lhqfgg8ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.dryCleaning',
  );
}
